language: php
dist: trusty
php:
    - 7.2
    - 7.3
    - 7.4
stages:
    - lint
    - test
    - report
before_install:
    - openssl aes-256-cbc -K $encrypted_589568f37856_key -iv $encrypted_589568f37856_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar -C tests/fixtures
    - pecl install grpc
install:
    - composer update --no-progress --no-interaction --no-suggest

script:
    - vendor/bin/phpunit --testsuite=unit

jobs:
    include:
        - stage: lint
          name: Code style check
          php: '7.2'
          script:
              - vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
        - stage: test
          name: Unit test
          script:
              - vendor/bin/phpunit --testsuite=integration
        - stage: report
          name: Code coverage
          php: '7.2'
          git:
              depth: false
          script:
              - vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=test-results.xml
              - sonar-scanner
          branches:
              only:
                  - master
                  - develop
cache:
    directories:
        - vendor
        - "$HOME/.composer/cache"
