language: php
dist: trusty
php:
    - 7.2
    - 7.3
    - 7.4
stages:
    - lint
    - test

install:
    - composer update --no-progress --no-interaction --no-suggest

jobs:
    include:
        - stage: lint
          name: Code style check
          php: '7.2'
          script:
              - vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
        - stage: test
          name: Test PHP 7.2
          php: '7.2'
          script:
              - vendor/bin/phpunit
        - stage: test
          name: Test PHP 7.3
          php: '7.3'
          script:
              - vendor/bin/phpunit
        - stage: test
          name: Test PHP 7.4
          php: '7.4'
          script:
              - vendor/bin/phpunit
cache:
    directories:
        - vendor
        - "$HOME/.composer/cache"
