language: php
dist: trusty

stages:
    - lint
    - test

install:
    - composer update --no-progress --no-interaction --no-suggest

script:
    - vendor/bin/phpunit

jobs:
    include:
        - stage: lint
          name: Code style check
          php: '7.2'
          script:
              - vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
        - stage: test
          name: Test PHP 7.2
          php: '7.2'
        - stage: test
          name: Test PHP 7.3
          php: '7.3'
        - stage: test
          name: Test PHP 7.4
          php: '7.4'
cache:
    directories:
        - vendor
        - "$HOME/.composer/cache"
